/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author usuario
 */
public class GUIPruebas extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form GUIPruebas
     */
    
    private int x = 10;
    private int y = 10;
    
    public GUIPruebas() {
        initComponents();
                ArrayList<JLabel> otros=new ArrayList();
        for(int i = 0; i <= 35; i++){
            
            JLabel labels = new JLabel();
            
            labels.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
           JFrame jf=new JFrame("Prueba");
        jf.setBackground(Color.BLACK);
        jf.setSize(new Dimension(200,70));
        jf.setVisible(true);
        jf.setDefaultCloseOperation(EXIT_ON_CLOSE);
        }
    });
        
            labels.setText(String.valueOf(i));
            labels.setIcon(new ImageIcon("agua.jpg"));
            switch(i){
                
                case 0: break;
                case 6: x += 101; y = 10; break;
                case 12: x += 101; y = 10; break;
                case 18: x += 101; y = 10; break;
                case 24: x += 101; y = 10; break;
                case 30: x += 101; y = 10; break;
                case 36: x += 101; y = 10; break;
                default: y += 101; break;
                
            }
            
            labels.setBounds(0 + x, 0 + y, 100, 100);
            this.add(labels);
            otros.add(labels);
            
        }
                    }
     
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPruebas().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
//                String numSelected = ((JButton) e.getSource()).getText();
//        

//        switch(posicion){
//            case 1: tf1.setText(numSelected); break;
//            case 2: tf2.setText(numSelected); break;
//            case 3: tf3.setText(numSelected); break;
//            case 4: tf4.setText(numSelected); break;
//            case 5: tf5.setText(numSelected); break;
//            case 6: tf6.setText(numSelected); break;
//            default: JOptionPane.showMessageDialog(null, "Ya se han insertado todos los números."); break;
//        }
//        
//        // ((JButton) e.getSource()).setEnabled(false); // Prueba para deshabilitar botones
//        
//        posicion += 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
